### ISSUE TITLE
Zlib returned error: -2

### ISSUE THREAD

**Issue by AnnanFay** [Mydayyy/ThisWarOfMineUnpacker#1]
I'm getting errors when trying to decompress the current Steam version of the files.

My experience compiling C++ programs is minimal so this may be an error on my part. I do not know enough about the system to track down the error myself, so any help would be appreciated.

I am using MSYS64 on Windows 10. After installing ZLIB the compilation process works and running the program works but gives errors. When running `-d` I get:

```
Extracting 'animations.dat'
Extracted file: 2660453
Zlib returned error: -2
Files may be incomplete
Extracting 'common.dat'
Extracted file: 5676721
Zlib returned error: -2
Files may be incomplete
Extracting 'gog.dat'
Extracted file: 1461901587
Extracting 'localizations.dat'
Extracted file: 158709524
Zlib returned error: -2
Files may be incomplete
Extracting 'scenes.dat'
Extracted file: 28553996
Zlib returned error: -2
Files may be incomplete
Extracting 'sounds.dat'
Extracted file: 2291986
Zlib returned error: -2
Files may be incomplete
Extracting 'templates.dat'
Extracted file: 1659982
Zlib returned error: -2
Files may be incomplete
Extracting 'textures-s3.dat'
Extracted file: 990417
Zlib returned error: -2
Files may be incomplete
Extracting 'videos.dat'
Extracted file: 672649299
Extracted file: 844235333
Extracted file: 1428999803
Extracted file: 2369948184
Extracted file: 4064823258
Extracted file: 4076067844
Extracting 'voices.dat'
```

Looking at available files lists several 0 size files.

If this program is broken with current files I recomend updating the README so other people do not waste time attempting to use as-is.
If it is still working then please let me know and I will invest more time trying to get this working on my system.

**Comment by Mydayyy** [comment]
Greetings,

I just redownloaded the game to test the unpacker, and it still seems to work. Atleast I was able to decompress the files without errors.

```
...
Extracted file: meshes/wood_house.texture
Extracted file: meshes/characters2/sasiad_kobieta_rat_przys_gruzem/sasoad_kobieta_rat_przys_gruzem.texture
Extracted file: meshes/atlasy/atlas_02_bogato_2_ds.texture
Extracted file: 4280044741
Extracted file: meshes/characters2/psycholog/psycholog_gora_nm_flip.texture
Extracted file: 4283708611
Extracted file: meshes/war_story_1/shelter_kominy_n.texture
Extracted file: 4290127292
Extracted file: meshes/characters2/dzieci/dziecko_julka/glowa_d.texture
Extracted file: 4291862642
Extracted file: 4293166846
Extracting 'videos.dat'
Extracted file: 672649299
Extracted file: war_child_black_and_white.ogv
Extracted file: 1428999803
Extracted file: 11bit_black_and_white_new.ogv
Extracted file: 4064823258
Extracted file: 4076067844
...
```

Two ideas that I can come up with: Either the game data structure is different on windows (that would certainly be interesting) or there might be an issue with your specific zlib version. What zlib version are you linking against?

Best Regards
Mydayyy
